"""Initial schema — autogenerated placeholder.

Run `alembic revision --autogenerate -m "initial"` to regenerate a full,
deterministic migration from `app.models`. This stub creates all tables from
the current metadata so `alembic upgrade head` works on a fresh database.
"""
from alembic import op
import sqlalchemy as sa  # noqa: F401

from app.database.session import Base
import app.models  # noqa: F401

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
